# Generated by Django 6.1 on 2026-08-08 17:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KES.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('donor_name', models.CharField(blank=True, default='Anonymous', max_length=150)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paystack', 'Paystack')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, db_index=True, help_text='CheckoutRequestID returned by the STK push, used to match the callback.', max_length=100, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.CharField(blank=True, default='general', help_text="What the donation is earmarked for, e.g. 'building-fund', 'missions-2026'.", max_length=150)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KES.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('donor_name', models.CharField(blank=True, default='Anonymous', max_length=150)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paystack', 'Paystack')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, db_index=True, help_text='CheckoutRequestID returned by the STK push, used to match the callback.', max_length=100, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giving_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('thanksgiving', 'Thanksgiving'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]